mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('school.urls', namespace='school')),
]

mysite/school/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from django.views.generic import CreateView, UpdateView, DeleteView

from django.urls import path, reverse_lazy

from django_ratelimit.decorators import ratelimit


from . import views
from .models import Student, Student_Class

app_name = 'school'

urlpatterns = [
    path('school/student-list/',
      (ratelimit(key='ip', method='GET', rate='10/m'))
      (login_required( views.StudentListView.as_view())),
       name='student-list'),
    path('', views.page, name='page'),
    path('accounts/login/', views.accounts_login, name='accounts-login'),
    path('accounts/logout/', views.accounts_logout, name='accounts-logout'),

    # path('accounts/login/', auth_views.LoginView.as_view(
    #     template_name='login.html',
    #     next_page='school:student-list'
    #     ),
    #     name='login-page'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(
    #     # template_name='logout.html',
    #     next_page='school:student-list'
    #     ),
    #     name='logout'),

    path('school/create/',
        CreateView.as_view(
        model=Student,
        fields='__all__',
        success_url=reverse_lazy('school:student-list'),
        template_name='generic_update.html'
        ),
        name='school-create'),
    path('school/<int:pk>/update/',
        UpdateView.as_view(
        model=Student,
        fields='__all__',
        success_url=reverse_lazy('school:student-list'),
        template_name='generic_update.html'
        ),
        name='school-update'),
    path('school/<int:pk>/delete/',
        DeleteView.as_view(
        model=Student,
        success_url=reverse_lazy('school:student-list'),
        template_name='generic_delete.html'
        ),
        name='school-delete'),

    path('class/',
     (ratelimit(key='ip', method='GET', rate='10/m'))
     (login_required(views.Student_ClassListView.as_view())),
      name='class-list'),
    path('class/create/',
        CreateView.as_view(
        model=Student_Class,
        fields='__all__',
        success_url=reverse_lazy('school:class-list'),
        template_name='generic_update.html'
        ),
        name='class-create'),
    path('class/<int:pk>/update/',
        UpdateView.as_view(
        model=Student_Class,
        fields='__all__',
        success_url=reverse_lazy('school:class-list'),
        template_name='generic_update.html'
        ),
        name='class-update'),
    path('school/<int:pk>/delete/',
        DeleteView.as_view(
        model=Student_Class,
        success_url=reverse_lazy('school:class-list'),
        template_name='generic_delete.html'
        ),
        name='class-delete'),
]

mysite/mysite/templates/generic_delete.html
{% block content %}

<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}

mysite/mysite/templates/generic_update.html
{% block content %}

<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}

mysite/mysite/templates/login.html
<h1> login </h1>

<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

mysite/mysite/templates/page.html
{{welcome}}


{% if request.user.is_superuser %}
    <br>
    <a href="{% url 'school:student-list' %}">studet list</a>
    <br>
    <a href="{% url 'school:class-list' %}">class list</a>
{% else %}
    <p> You aren't superuser</p>
{% endif %}
<br>
<a href="{% url 'school:accounts-logout' %}">logout</a>